In [108]:
import numpy as np

# 创建ndarray

In [109]:
data1 = [6,7,8,9,0]
arr1 = np.array(data1)
arr1

array([6, 7, 8, 9, 0])

In [110]:
data2 = [[6,7,8],[9,0,1]]
arr2 = np.array(data2)
arr2

array([[6, 7, 8],
       [9, 0, 1]])

## 显示数组参数

In [111]:
arr2.ndim

2

In [112]:
arr2.shape

(2, 3)

In [113]:
arr2.dtype

dtype('int32')

## 初始化
全0、全1、对角数组

In [114]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [115]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [116]:
np.ones((3,6))

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [117]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [118]:
aaa = np.zeros((3,6))
np.ones_like(aaa)     # 类似大小的数组

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

## arange列表

In [119]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## ndarray数据类型
dtype, astype

In [120]:
data2 = [[6,7,8],[9,0,1]]
arr2 = np.array(data2, dtype=np.int64)
arr2
arr2.dtype

dtype('int64')

In [121]:
float_atrr = arr2.astype(np.float64)
float_atrr
float_atrr.dtype

dtype('float64')

In [122]:
strings_atrr = arr2.astype(np.string_)
strings_atrr
strings_atrr.dtype

dtype('S21')

In [123]:
strings_atrr = arr2.astype(arr1.dtype)
strings_atrr
strings_atrr.dtype

dtype('int32')

# 数组与标量之间运算

In [124]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr
arr*arr
arr-arr
1/arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

## 最大值操作

In [125]:
a = ['1', '2', '5', '3']
b = np.array(a)
b

array(['1', '2', '5', '3'], 
      dtype='|S1')

In [126]:
max(b)

'5'

In [127]:
b.argmax()    # 最大值所在的索引

2

# 基本的索引和且切片

In [128]:
arr = np.arange(10)
arr[:]
arr[5]
arr[1:3]        # 算头不算尾

array([1, 2])

In [129]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]   # 第3行

array([7, 8, 9])

## 索引与切片

In [130]:
arr2d[0][2]
arr2d[0,2]

arr2d[:2]
arr2d[:2,1:]
arr2d[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

## 布尔索引

In [131]:
arr2d2 = arr2d
arr2d2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [132]:
arr2d2<7

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]], dtype=bool)

In [133]:
arr2d2[arr2d2<7] = 5
arr2d2

array([[5, 5, 5],
       [5, 5, 5],
       [7, 8, 9]])

## 转置

In [134]:
arr2d2.T

array([[5, 5, 7],
       [5, 5, 8],
       [5, 5, 9]])

# 随机矩阵

In [135]:
aa=np.random.randn(2, 3)
aa

array([[ 0.02533771, -0.39449184,  1.02661675],
       [ 0.88406079,  0.67040376,  0.06911419]])

In [136]:
# 转成1维
aa.ravel()

array([ 0.02533771, -0.39449184,  1.02661675,  0.88406079,  0.67040376,
        0.06911419])

In [137]:
# 转成1维
aa.reshape(-1)

array([ 0.02533771, -0.39449184,  1.02661675,  0.88406079,  0.67040376,
        0.06911419])

In [138]:
# 转成3行
aa.reshape(3,-1)

array([[ 0.02533771, -0.39449184],
       [ 1.02661675,  0.88406079],
       [ 0.67040376,  0.06911419]])

In [139]:
# 复制
np.tile(aa,2)

array([[ 0.02533771, -0.39449184,  1.02661675,  0.02533771, -0.39449184,
         1.02661675],
       [ 0.88406079,  0.67040376,  0.06911419,  0.88406079,  0.67040376,
         0.06911419]])

In [140]:
np.tile(aa,(2,1))

array([[ 0.02533771, -0.39449184,  1.02661675],
       [ 0.88406079,  0.67040376,  0.06911419],
       [ 0.02533771, -0.39449184,  1.02661675],
       [ 0.88406079,  0.67040376,  0.06911419]])

# 转为字典及排序

In [141]:
key = ['Jim','Bob','Alice']
val = [1, 3, 2]
dict_aa = dict(zip(key,val))
dict_aa

{'Alice': 2, 'Bob': 3, 'Jim': 1}

## 排序

In [148]:
# 降序
lst = dict_aa
sorted(lst.items(), key=lambda x: -x[1])

[('Bob', 3), ('Alice', 2), ('Jim', 1)]

In [143]:
# 升序
lst = dict_aa
sorted(lst.items(), key=lambda x: x[1])

[('Jim', 1), ('Alice', 2), ('Bob', 3)]

In [144]:
# 按key排序
lst = dict_aa
sorted(lst.items(), key=lambda x: x[0], reverse=True)        # 非数字不可用-x形式，使用reverse关键字

[('Jim', 1), ('Bob', 3), ('Alice', 2)]

## 取Top N的key

In [145]:
key = ['Jim','Bob','Alice']
val = [1, 3, 2]
np.array(key)[np.argsort(val)]

array(['Jim', 'Alice', 'Bob'], 
      dtype='|S5')

In [146]:
n = 2
np.array(key)[np.argsort(val)][:-(n+1):-1]

array(['Bob', 'Alice'], 
      dtype='|S5')