In [2]:
import numpy as np

# jupyter 画图
%matplotlib inline 

In [62]:
# 初始数据集
dataX = np.array([[1,2,3],[4,5,6],[7,8,9]])
dataX = dataX.astype(np.float64)
dataX

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

# 标准化（规范化），返回值为标准化后的数据
x = (x-mean)/sigma

In [63]:
from sklearn.preprocessing import StandardScaler
StandardScaler().fit_transform(dataX)

array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])

In [65]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(dataX)
scalerX = scaler.transform(dataX)
scalerX

array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])

# 区间缩放，返回值为缩放到[0, 1]区间的数据
x = (x-xmin)/(xmax-xmin)

In [66]:
from sklearn.preprocessing import MinMaxScaler
MinMaxScaler().fit_transform(dataX)

array([[ 0. ,  0. ,  0. ],
       [ 0.5,  0.5,  0.5],
       [ 1. ,  1. ,  1. ]])

# 归一化，转化为“单位向量”
基于特征矩阵的行，将样本向量转换为“单位向量”

In [67]:
from sklearn.preprocessing import Normalizer
Normalizer().fit_transform(dataX)

array([[ 0.26726124,  0.53452248,  0.80178373],
       [ 0.45584231,  0.56980288,  0.68376346],
       [ 0.50257071,  0.57436653,  0.64616234]])

In [75]:
xx = Normalizer().fit_transform(dataX)
np.vdot(xx[0,:],xx[0,:])

1.0

# 二值化

In [82]:
dataX

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [80]:
from sklearn.preprocessing import Binarizer
Binarizer(threshold=3).fit_transform(dataX)

array([[ 0.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

# 分类变量编码

In [87]:
x = np.array(['M','F','M','M','F','M'])
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
x_label = enc.fit_transform(x)
x_label

array([1, 0, 1, 1, 0, 1])

# 独热编码

In [32]:
from sklearn.preprocessing import OneHotEncoder
xx =OneHotEncoder().fit_transform(x_label.reshape(-1,1))
type(xx)
print xx

  (0, 1)	1.0
  (1, 0)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 0)	1.0
  (5, 1)	1.0


# 计算缺失值

In [50]:
x = np.array([[np.nan,2,6],[6,np.nan,5],[2,8,np.nan]])
x 

array([[ nan,   2.,   6.],
       [  6.,  nan,   5.],
       [  2.,   8.,  nan]])

In [51]:
from sklearn.preprocessing import Imputer
Imputer(missing_values='NaN', strategy='mean',axis=0).fit_transform(x)   #  按列填充

array([[ 4. ,  2. ,  6. ],
       [ 6. ,  5. ,  5. ],
       [ 2. ,  8. ,  5.5]])

In [53]:
from sklearn.preprocessing import Imputer
Imputer(missing_values='NaN', strategy='mean',axis=1).fit_transform(x)   #  按行填充

array([[ 4. ,  2. ,  6. ],
       [ 6. ,  5.5,  5. ],
       [ 2. ,  8. ,  5. ]])

# 数据变换

## 生成多项式特征

In [85]:
dataX

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [84]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(2)
poly.fit_transform(dataX)

array([[  1.,   1.,   2.,   3.,   1.,   2.,   3.,   4.,   6.,   9.],
       [  1.,   4.,   5.,   6.,  16.,  20.,  24.,  25.,  30.,  36.],
       [  1.,   7.,   8.,   9.,  49.,  56.,  63.,  64.,  72.,  81.]])

## 自定义转换函数
log1p：log(1+x)

In [88]:
from numpy import log1p
from sklearn.preprocessing import FunctionTransformer
FunctionTransformer(log1p).fit_transform(dataX)

array([[ 0.69314718,  1.09861229,  1.38629436],
       [ 1.60943791,  1.79175947,  1.94591015],
       [ 2.07944154,  2.19722458,  2.30258509]])

In [89]:
log1p(1)

0.69314718055994529

In [90]:
log1p(dataX)

array([[ 0.69314718,  1.09861229,  1.38629436],
       [ 1.60943791,  1.79175947,  1.94591015],
       [ 2.07944154,  2.19722458,  2.30258509]])